{"name": "test_prime[0]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False == True", "trace": "self = <TestPrime.TestPrime object at 0x0000021E421432B0>, data = 0\n\n    def test_prime(self,data):\n        result = self.prime(data)\n>       assert result==True\nE       assert False == True\n\nTestPrime.py:24: AssertionError"}, "attachments": [{"name": "stdout", "source": "01fd614c-6800-4511-a1ee-7eb1102c6d2a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "0"}], "start": 1665924409074, "stop": 1665924409075, "uuid": "29e385af-9e0b-4f57-b69c-fd3ff3f523c3", "historyId": "5a5614ac4e0e7b5d706ebe217f74d9ab", "testCaseId": "29c2fc516ba3d064a8ea2e5f20a639b6", "fullName": "TestPrime.TestPrime#test_prime", "labels": [{"name": "suite", "value": "TestPrime"}, {"name": "subSuite", "value": "TestPrime"}, {"name": "host", "value": "DESKTOP-0AC7NBS"}, {"name": "thread", "value": "30748-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestPrime"}]}