{"name": "test_prime[-1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False == True", "trace": "self = <TestPrime.TestPrime object at 0x0000021E421430A0>, data = -1\n\n    def test_prime(self,data):\n        result = self.prime(data)\n>       assert result==True\nE       assert False == True\n\nTestPrime.py:24: AssertionError"}, "attachments": [{"name": "stdout", "source": "2abd9cb7-2147-4deb-a589-1aa3f5656294-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "-1"}], "start": 1665924409007, "stop": 1665924409008, "uuid": "7c3e9e45-65a4-4a53-8dd4-6a6becb7f960", "historyId": "63bdade243026df7e232ec236dd6ada5", "testCaseId": "29c2fc516ba3d064a8ea2e5f20a639b6", "fullName": "TestPrime.TestPrime#test_prime", "labels": [{"name": "suite", "value": "TestPrime"}, {"name": "subSuite", "value": "TestPrime"}, {"name": "host", "value": "DESKTOP-0AC7NBS"}, {"name": "thread", "value": "30748-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestPrime"}]}